.TH NOVENA-EEPROM-GUI 1 "13 Oct 2014" Novena "Linux System Administration"
.SH NAME
novena-eeprom-gio \- View and modify a Novena's EEPROM
.SH SYNOPSIS
.B novena-eeprom-gui

.SH DESCRIPTION
.LP
Novena ships with an EEPROM that contains various hardcoded settings.  Among
these include Gigabit Ethernet MAC address, serial number, and display timings.
.B novena-eeprom-gui
can be used to inspect and modify these settings.  Additionally, it can make
backups of EEPROM files and restore backups to the EEPROM.
.SH AUTHORS
Written by Sean Cross <xobs@kosagi.com>
